theme: minima
title: Get On My Wave by Andrew Mcmahon
author: Kevin Olanday
email: kevinwillcode@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A new single from Andrew Mcmahon In The Wilderness

# social links
twitter_username: dearyad # DO NOT include the @ character, or else the build will fail!
github_username:  kevinolanday # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
